name: CI workflow

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_iOS:
    name: Build and Test project on iOS
    runs-on: [ self-hosted, iOS ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: xcodebuild -scheme ios-features-Package build -sdk iphonesimulator -destination "generic/platform=iOS"
      - name: Test
        run: xcodebuild -scheme ios-features-Package test -destination "platform=iOS Simulator,name=iPhone 17,OS=latest"
